# Site settings
title: Catto Electronics
description: "" # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://Catto-Electronics.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
logo: "assets/img/branding/Rafael-main-site-logo.png"
logo-icon: "assets/img/branding/Rafael-site-logo.png"
logo-icon-SEO: "assets/img/branding/Rafael-site-logo.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",

# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "assets/img/branding/Rafael-main-site-logo.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Catto Electronics # add your name
author-pic: Rafael-headshot.jpg
about-author: Lorem ipsum.

# Contact links
email: 
phone: # Add your Phone number
website: https://Catto-Electronics.github.io # Add your website
linkedin: 
github: Catto-Electronics
twitter: # Add your Twitter handle
bandcamp: # Add your Bandcamp username
stackoverflow: # Add your stackoverflow account

# Newsletter | something other than mailchimp
mailchimp: #"https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: # Google Analytics tag ID
fbadmin: # Facebook ID admin

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: Catto-Electronics/Catto-Electronics.github.io # The GitHub repo URL.  https://utteranc.es/
  issue_term: title # The GitHub issue label
  label: # The GitHub comments label
  theme: preferred-color-scheme # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]